### ISSUE TITLE
您好，以下是发现部分界面问题

### ISSUE THREAD

**Issue by owmjess** [tumobi/nideshop#1]
## **您好，以下是发现部分界面问题：**
- 分类页：滑动页面左栏不能固定
- 分类商品页：点顶部子分类建议加载显示loading
- 购物车页：无法修改数量
- 商品详情页：选择规格数量，建议做成有赞那种（点击加入购物车，弹出规格和数量）
- 下单页：收货地址建议整合微信地址库
- 下单页：选择优惠券建议可以选择会员中心优惠券数据
- 专题详情页：留言没有新增效果，查看更多没反应

**Comment by tumobi** [comment]
反馈的问题回在近期修复，谢谢

**Comment by tumobi** [comment]
@owmjess 专题留言发布、查看更多已添加

**Comment by owmjess** [comment]
看到了，群主高效率，其他修改计划啥时候更新，最近想用这套试试
