### ISSUE TITLE
请问一下这是什么情况。。。

### ISSUE THREAD

**Issue by gzjiangying** [tumobi/nideshop#20]
| {"errno":0,"errmsg":"","data":{"banner":[{"id":1,"ad_position_id":1,"media_type":1,"name":"合作 谁是你的菜","link":"","image_url":"http://yanxuan.nosdn.127.net/65091eebc48899298171c2eb6696fe27.jpg","content":"合作 谁是你的菜","end_time":0,"enabled":1},{"id":2,"ad_position_id":1,"media_type":1,"name":"活动 美食节","link":"","image_url":"http://yanxuan.nosdn.127.net/bff2e49136fcef1fd829f5036e07f116.jpg","content":"活动 美食节","end_time":0,"enabled":1},{"id":3,"ad_position_id":1,"media_type":1,"name":"活动 母亲节","link":"","image_url":"http://yanxuan.nosdn.127.net/8e50c65fda145e6dd1bf4fb7ee0fcecc.jpg","content":"活动 母亲节","end_time":0,"enabled":1}],"channel":[{"id":1,"name":"居家","url":"/pages/category/category?id=1005000","icon_url":"http://ac-3yr0g9cz.clouddn.com/c031ea3cf575f885cd1c.png","sort_order":1},{"id":2,"name":"餐厨","url":"/pages/category/category?id=1005001","icon_url":"http://ac-3yr0g9cz.clouddn.com/4fbe8913819b017ebe1b.png","sort_order":2},{"id":3,"name":"配件","url":"/pages/category/category?id=1008000","icon_url":"http://ac-3yr0g9cz.clouddn.com/e8070853e6c6f5627713.png","sort_order":3},{"id":4,"name":"服装","url":"/pages/category/category?id=1005002","icon_url":"http://ac-3yr0g9cz.clouddn.com/4fa3c0c72964901c5a45.png","sort_order":4},{"id":5,"name":"志趣","url":"/pages/category/category?id=1019000","icon_url":"http://ac-
-- | --

**Comment by whughchen** [comment]
正常情况

**Comment by gzjiangying** [comment]
是没有配置数据吗？

**Comment by tumobi** [comment]
这是 api 接口，已经配置正确，请配合 https://github.com/tumobi/nideshop-mini-program 使用
