### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by jj89757hhb** [tumobi/nideshop#32]
xuetianhhbdeMac-mini:~ xuetianhhb$ npm install
npm WARN enoent ENOENT: no such file or directory, open '/Users/xuetianhhb/package.json'
npm WARN xuetianhhb No description
npm WARN xuetianhhb No repository field.
npm WARN xuetianhhb No README data
npm WARN xuetianhhb No license field.
xuetianhhbdeMac-mini:~ xuetianhhb$

**Comment by WeijianHuang** [comment]
@jj89757hhb 你的路径错了。应改到nideshop根目录
