### ISSUE TITLE
后台管理系统

### ISSUE THREAD

**Issue by darriel** [tumobi/nideshop#38]
麻烦问一下作者什么时候会做后台管理系统，非常感谢！

**Comment by gglinux** [comment]
看了代码，层次很清晰，非常棒！希望快上后台管理系统，非常感谢！

**Comment by darriel** [comment]
我也仔细看了一下最近，代码非常清楚，近乎于最佳工程实践，很少看到这么良心的作品。楼上微信多少，可否交流一下。我的15900563930

**Comment by ZheGuangZeng** [comment]
谢谢作者！！！期待后台管理系统！！！

**Comment by sherry2017** [comment]
我npm start 报错，，async getTemplateContent()  Unexpected identifier

**Comment by tumobi** [comment]
> 我npm start 报错，，async getTemplateContent() Unexpected identifier

检查 Node.js 是不是 8.x 以上版本
