### ISSUE TITLE
加入购物车时底部栏位不显示

### ISSUE THREAD

**Issue by nlmayday** [tumobi/nideshop#4]
这个问题在开发工具上不出现，在手机上会出现.
在物品详情页点击加入购物车后，跳转的下一个场景页面底部栏位不显示

**Comment by JO-WTF** [comment]
我也有遇到这个问题。

看一下我的branch，删掉了下一个场景页面，直接在详情页选择规格调整数量。

**Comment by nlmayday** [comment]
好的 tks

**Comment by kanoyami** [comment]
这个bug只会在ios上出现，原因是在添加的界面里，选择详情的view太短，系统默认的边界会覆盖下面的按钮，在样式里给attr-pop设置一个定高就行了。
