### ISSUE TITLE
为什么出现500错误

### ISSUE THREAD

**Issue by samwang2017** [tumobi/nideshop#40]
### ### `[root@hZ ~]# curl -I http://127.0.0.1:8360/
HTTP/1.1 500 Internal Server Error
Vary: Origin
X-Powered-By: thinkjs-3.2.8
Content-Type: text/html; charset=utf-8
Content-Length: 87146
Date: Wed, 15 Aug 2018 07:41:33 GMT
Connection: keep-alive
`

**Comment by tumobi** [comment]
先使用 npm start 启动程序，查看控制台报错信息

**Comment by samwang2017** [comment]
`[root@iZuf6iu5vj7lifng3h372hZ init.d]# curl -I http://127.0.0.1:8360/
HTTP/1.1 200 OK
Vary: Origin
X-Powered-By: thinkjs-3.2.8
Content-Type: application/json; charset=utf-8
X-Response-Time: 37ms
Content-Length: 18622
Date: Fri, 17 Aug 2018 07:59:08 GMT
Connection: keep-alive
`
现在正常了  可以正常获取数据，问题出在mysql的免密登陆上面

**Comment by samwang2017** [comment]
`[root@iZZ init.d]# curl -I http://127.0.0.1:8360/ HTTP/1.1 200 OK Vary: Origin X-Powered-By: thinkjs-3.2.8 Content-Type: application/json; charset=utf-8 X-Response-Time: 37ms Content-Length: 18622 Date: Fri, 17 Aug 2018 07:59:08 GMT Connection: keep-alive
现在正常了 可以正常获取数据，问题出在mysql的免密登陆上面`
