### ISSUE TITLE
SSL配置问题

### ISSUE THREAD

**Issue by MarcHe124** [tumobi/nideshop#53]
使用acme自动配置SSL，在middleware.js里添加了
{
    handle: 'resource',
    enable: isDev,
    options: {
      root: path.join(think.ROOT_PATH, 'www'),
      publicPath: /^\/(static|favicon\.ico|index\.html|web\.js|styles\.css|fonts|\.well-known|well-known|\.well-known\/acme-challenge)/
    }
  },

试了一下，SSL验证key文件在www里放在well-known/acme-challenge文件夹下的可以访问到，但在.well-known/acme-challenge下访问不到，不知道是为什么

**Comment by tumobi** [comment]
.well-known 转义下前面的 `.` 试试

**Comment by MarcHe124** [comment]
怎么转义？  publicPath: /^\/(static|favicon\.ico|index\.html|web\.js|styles\.css|fonts|\.well-known|well-known|\.well-known\/acme-challenge)/  

这样设了还是不行

**Comment by MarcHe124** [comment]
或者如果短暂给更广泛的匹配可以work吗？比如如何开放www整个文件夹之类

**Comment by tumobi** [comment]
@MarcHe124 www 下的文件建议使用 nginx 访问。

**Comment by MarcHe124** [comment]
这个没有解决问题呀。。
