### ISSUE TITLE
商品详情页报错

### ISSUE THREAD

**Issue by hiro086** [tumobi/nideshop#57]
按教程部署到SAE，测试接口发现获取对应商品报404，/api/goods/list等其他接口正常，/api/goods/goods?id=xxx报错。
`
logic deprecated logic's __after method is deprecated, it will be discarded in the next version node_modules/koa-compose/index.js:42:32
logic deprecated logic's __after method is deprecated, it will be discarded in the next version node_modules/koa-compose/index.js:42:32
{ NotFoundError: url `/api/goods/goods` not found. at Object.throw (/var/www/nideshop/node_modules/koa/lib/context.js:97:11) at beforeTrace.then.then (/var/www/nideshop/node_modules/think-trace/lib/index.js:33:23) at process._tickCallback (internal/process/next_tick.js:68:7) 
message: 'url `/api/goods/goods` not found.' } { request: { method: 'GET', url: '/api/goods/goods?id=1181000', header: { 'x-forwarded-for': '58.213.91.10, 58.213.91.10', host: 'yizaohuadian2.applinzi.com', appname: 'yizaohuadian2', appversion: '1', accesskey: 'nxz33x2z4y', secretkey: '2mxi11xkz3hkmx1y34m0mmwzy4y2z03k03hz0m1w', apphash: '273', mysqlport: '0', appcookie: 'default_version=1;saedomain=8;', appmask: '1', appsrvc: '0000000000000000', ipid: '23024', 'x-real-ip': '58.213.91.10', 'x-proto': 'SSL', 'x-forwarded-proto': 'https', 'upgrade-insecure-requests': '1', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36', accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'zh-CN,zh;q=0.9' } }, response: { status: 404, message: 'Not Found', header: [Object: null prototype] { vary: 'Origin', 'x-powered-by': 'thinkjs-3.2.10' } }, app: { subdomainOffset: 2, proxy: true, env: 'production' }, originalUrl: '/api/goods/goods?id=1181000', req: '<original node req>', res: '<original node res>', socket: '<original node socket>' }
`

**Comment by tumobi** [comment]
404 错误。没有 /api/goods/goods 这个地址
