### ISSUE TITLE
首页耗时太多，有什么解决办法吗

### ISSUE THREAD

**Issue by wangdejun** [tumobi/nideshop#62]
如题
首页耗时太多，发现执行了大量的Sql, 在本地数据库看不出来，稍微慢点的数据库首页就超时，有什么好的解决办法？
https://github.com/tumobi/nideshop/blob/cf81d741943320241b4e2b4163e54a728181efe5/src/api/controller/index.js#L4

**Comment by tumobi** [comment]
缓存下查询的结果 或 数据库配置增加。
