### ISSUE TITLE
打算使用 Egg.js 重构服务端，大家有什么建议？

### ISSUE THREAD

**Issue by tumobi** [tumobi/nideshop#69]

**Comment by 375298853** [comment]
赶紧的#89.。

**Comment by epsv4** [comment]
https://github.com/midwayjs/midway
直接一步到位吧。。
如果觉得工程太大，可以把框架搭好了 ，然后社区实现模块

**Comment by tumobi** [comment]
@epsv4 最近关注 nest.js 多些，有空再了解下 midway

**Comment by Kenshinhu** [comment]
想问一下最后是打算是用eggjs 还是 nestjs重构？

**Comment by tumobi** [comment]
> 想问一下最后是打算是用eggjs 还是 nestjs重构？

eggjs

**Comment by Kenshinhu** [comment]
> > 想问一下最后是打算是用eggjs 还是 nestjs重构？
> 
> eggjs

希望能参与开发
